version: 0.0
os: linux

hooks:
  # Stop and delete running containers before installation of the new application
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300       
      runas: root       

  #  Run a quick check to see if Docker is installed and installs it if not
  BeforeInstall:
    - location: scripts/check_docker.sh
      timeout: 60         
      runas: root     

  # AfterInstall runs to start the container after the deployment is complete
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300       
      runas: root         