version: 0.2  # Specifies the AWS CodeBuild buildspec file version.

env:
  parameter-store:      # Retrieve secrets from AWS SSM Parameter Store.
    DOCKER_REGISTRY_USERNAME: /my-app/image-repo/username
    DOCKER_REGISTRY_PASSWORD: /my-app/image-repo/password   
    DOCKER_REGISTRY_URL: /my-app/image-repo/registry-url  

phases:
  pre_build:
    commands:
      - set -eo pipefail
      - echo "::Logging in to Registry..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - echo "::Login successful!"

  build:
    commands:
      - echo "::Building Docker Image..."
      # Build the Docker image 
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-ci-cd-demo:latest" .   
      - echo "::Build completed successfully!"  

  post_build:
    commands:
      - echo "::Pushing image to registry..."   
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-ci-cd-demo:latest"   
      - echo "::Image pushed successfully!"
